### ISSUE TITLE
How to encode constants

### ISSUE THREAD

**Issue by cch1** [ztellman/gloss#43]
I would like to prefix all encoded frames with a constant string of two bytes that should be discarded on decode.  I have determined that `(gloss/compile-frame ["AB" :byte])` does the opposite of what I want (it does not encode the prefix "AB", but injects it into the decoded value).  How can encode such a constant?  It seems clunky to provide pre- and post- decoders to accomplish the task.

**Comment by cch1** [comment]
Looking at this blog post (https://paulosuzart.github.io/blog/2012/07/09/tcp-server-with-clojure-aleph-and-gloss/), I don't think my confusion is unique -his PUT example does not match his stated requirements due to the handling of the constant "PUT" string.

**Comment by ztellman** [comment]
Hi, sorry for the late response on this.  It is a bit clunky to use the pre and post decoders, but that's the best the current implementation has to offer.
